// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertPDFToImages() {
  return window['go']['main']['App']['ConvertPDFToImages']();
}

export function GetReply(arg1) {
  return window['go']['main']['App']['GetReply'](arg1);
}

export function InitScanner(arg1) {
  return window['go']['main']['App']['InitScanner'](arg1);
}

export function SetDirectory() {
  return window['go']['main']['App']['SetDirectory']();
}

export function UploadDocuments() {
  return window['go']['main']['App']['UploadDocuments']();
}
