// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function ConvertPDFToImages():Promise<void>;

export function GetReply(arg1:string):Promise<string>;

export function InitScanner(arg1:string):Promise<fs.FileScanner>;

export function SetDirectory():Promise<string>;

export function UploadDocuments():Promise<void>;
